---
# tasks file for ansible-squid

- include_tasks: set_facts.yml

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: config_squid.yml

- include_tasks: config_squid_transparent_proxy.yml
  when:
    - squid_transparent_proxy
    - squid_transparent_proxy_ferm

- include_tasks: setup-basic-auth.yml
